# jstest-gtk - A graphical joystick tester
# Copyright (C) 2018 Ingo Ruhnke <grumbel@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

image: ubuntu:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get -qq update
  - apt-get -qq -y install lsb-release
  - lsb_release -a
  - apt-get -qq -y install
    build-essential
    git
    cmake
    g++-8
    g++-5
    clang-6.0
    libgtkmm-3.0-dev
    libsigc++-2.0-dev
    libx11-dev
    pkg-config
    x11proto-core-dev

.build_jstest_gtk_template: &build_jstest_gtk
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWARNINGS=ON -DWERROR=ON
    - make VERBOSE=1
    # - make test VERBOSE=1 ARGS="-V"

build:gcc5:release:
  <<: *build_jstest_gtk
  variables:
    CXX: "g++-5"
    BUILD_TYPE: "Release"

build:gcc:release:
  <<: *build_jstest_gtk
  variables:
    CXX: "g++-8"
    BUILD_TYPE: "Release"

build:clang:release:
  <<: *build_jstest_gtk
  variables:
    CXX: "clang++-6.0"
    BUILD_TYPE: "Release"

build:gcc5:debug:
  <<: *build_jstest_gtk
  variables:
    CXX: "g++-5"
    BUILD_TYPE: "Debug"

build:gcc:debug:
  <<: *build_jstest_gtk
  variables:
    CXX: "g++-8"
    BUILD_TYPE: "Debug"

build:clang:debug:
  <<: *build_jstest_gtk
  variables:
    CXX: "clang++-6.0"
    BUILD_TYPE: "Debug"

# EOF #
